title: Blog by VB
author: Vedavi Balji
email: vedavi.balaji@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first website.
# social links
instagram_username: you.knowwho
github_username: VedaviBalaji

show_excerpts: true # set to false to remove excerpts on the homepage

theme: Architect
